{
    "status": "Success",
    "data": {
        "dealers": [
            {
                "id": 306,
                "name": "ABC MOT.ARÇ.SAN.VE TİC.AŞ.",
                "shortName": "ABC UYDU",
                "code": "98443",
                "mainCode": "98131",
                "address": "MERKEZ MAH. CENDERE YOLU NO:12",
                "district": "KAĞITHANE",
                "city": "İSTANBUL",
                "latitude": 41.084259,
                "longitude": 28.977885,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 311,
                "name": "BATMAN MOTORLU ARAÇLAR SANAYİ TİCARET ANONİM ŞİRKETİ",
                "shortName": "BATMAN",
                "code": "98447",
                "mainCode": "98447",
                "address": "GÜLTEPE MAH KIBRIS ŞEHİTLERİ BLV TEKSTİL KENT KARŞISI ESKİ HAVA LİMANI KAVŞAĞI NO:132",
                "district": "MERKEZ",
                "city": "BATMAN",
                "latitude": 37.90955,
                "longitude": 41.11659,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 167,
                "name": "FIRAT OTOM. TİC. VE SAN. A.Ş.",
                "shortName": "FIRAT",
                "code": "63105",
                "mainCode": "63105",
                "address": "YENİCE MAH. AKÇAKALE CAD. NO:285",
                "district": "EYYÜBİYE",
                "city": "ŞANLIURFA",
                "latitude": 37.06302,
                "longitude": 38.49362,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 201,
                "name": "GÖÇMENTÜRK DYN. TK. ML. TİC. VE TRZ. LTD. ŞTİ.",
                "shortName": "GÖÇMENTÜRK",
                "code": "07302",
                "mainCode": "07110",
                "address": "D400 KARAYOLU KEMER MAH.SİDE KAVŞAĞI TESPO YANI",
                "district": "MANAVGAT",
                "city": "ANTALYA",
                "latitude": 36.785706,
                "longitude": 31.414257,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 305,
                "name": "ATILGAN FİLO VE SATIŞ SONRASI HİZMETLERİ LOJİSTİK SAN. TİC. A.Ş.",
                "shortName": "ATILGAN RİZE",
                "code": "98438",
                "mainCode": "98438",
                "address": "HAMİDİYE MAH. GÜNDOĞDU MEVKİİ NO:349",
                "district": "MERKEZ",
                "city": "RİZE",
                "latitude": 41.05032,
                "longitude": 40.611511,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 261,
                "name": "ERNAZ OTOM. SAN. TİC. VE PAZ. A.Ş.",
                "shortName": "ERNAZ",
                "code": "41402",
                "mainCode": "41106",
                "address": "ŞİRİNTEPE MEVKİİ POLİS LOJMANLARI YOLU",
                "district": "KURUÇEŞME",
                "city": "KOCAELİ",
                "latitude": 40.762347,
                "longitude": 29.87061,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 174,
                "name": "GÜLPAR MOTORLU ARAÇLAR EV GEREÇLERİ TURZ.SEYH.NAK. SAN. VE TİC.A.Ş.",
                "shortName": "GÜLPAR",
                "code": "38107",
                "mainCode": "38107",
                "address": "ANBAR MAH. OSMAN KAVUNCU BULVARI NO:538",
                "district": "MELİKGAZİ",
                "city": "KAYSERİ",
                "latitude": 38.45143,
                "longitude": 35.20438,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 258,
                "name": "GÜNERLER OTOM.  A.Ş.",
                "shortName": "GÜNERLER",
                "code": "34136",
                "mainCode": "34136",
                "address": "FATİH SULTAN MEHMET MH. ALEMDAĞ CD. NO:193",
                "district": "ÜMRANİYE",
                "city": "İSTANBUL",
                "latitude": 41.0209,
                "longitude": 29.1214,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 181,
                "name": "GÜRSOY OTO SAN. VE TİC. LTD. ŞTİ.",
                "shortName": "GÜRSOY",
                "code": "33109",
                "mainCode": "33109",
                "address": "AKDENİZ MH. GMK BULVARI NO:546",
                "district": "MEZİTLİ",
                "city": "MERSİN",
                "latitude": 36.73951,
                "longitude": 34.517593,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 288,
                "name": "GÜRSOY OTO SAN. VE TİC. LTD. ŞTİ.",
                "shortName": "GÜRSOY",
                "code": "98425",
                "mainCode": "33109",
                "address": "Zeki Ayan Mah. Akbelen Blv. N0.56/A",
                "district": "TOROSLAR",
                "city": "MERSİN",
                "latitude": 36.8132,
                "longitude": 34.6072,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 221,
                "name": "KUTAY MOT.ARÇ. TRZ. TAŞIMACILIK, İNŞAAT, AKARYAKIT SAN.TİC.AŞ.",
                "shortName": "KUTAY",
                "code": "48403",
                "mainCode": "48108",
                "address": "MERKEZ MAH. ATATÜRK BULVARI NO:299 KONACIK",
                "district": "BODRUM",
                "city": "MUĞLA",
                "latitude": 37.055709,
                "longitude": 27.366125,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 300,
                "name": "KUTAY MOT.ARÇ. TRZ. TAŞIMACILIK, İNŞAAT, AKARYAKIT SAN.TİC.AŞ.",
                "shortName": "KUTAY",
                "code": "98422",
                "mainCode": "48108",
                "address": "Çamköy mah. Mareşal Fevzi Çakmak Bulvarı No: 61/1 Fethiye/ Muğla",
                "district": "FETHİYE",
                "city": "MUĞLA",
                "latitude": 36.694694,
                "longitude": 29.075071,
                "isRenew": false,
                "isService": false,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 280,
                "name": "NAS OTO PETR.SERV.HIZ. SAN.VE TIC.LTD.STI.",
                "shortName": "NAS",
                "code": "98430",
                "mainCode": "98430",
                "address": "TURGUT ÖZAL MAHALLESİ MARDİN CADDESİ HAVALİMANI YANI",
                "district": "KIZILTEPE",
                "city": "MARDİN",
                "latitude": 37.14003,
                "longitude": 40.38016,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 163,
                "name": "NAZAR OTOMOBİLCİLİK YEDEK PARÇA TURİZM NAKLİYAT İNŞAAT VE TİC.LTD.ŞTİ",
                "shortName": "NAZAR",
                "code": "35123",
                "mainCode": "35123",
                "address": "BÖLGE TRAFİK YANI ÇANAKKALE CAD. NO:9",
                "district": "MENEMEN",
                "city": "İZMİR",
                "latitude": 38.6175,
                "longitude": 27.0637,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 212,
                "name": "NESİL OTOM.YEDEK PARÇA SERVİS HİZMETLERİ TİC.LTD.ŞTİ.",
                "shortName": "NESİL",
                "code": "34439",
                "mainCode": "34701",
                "address": "KAPTANPAŞA MAH. PİYALEPAŞA BULVARI FAMAS PLAZA C BLOK APT. NO:75A/A",
                "district": "ŞİŞLİ",
                "city": "İSTANBUL",
                "latitude": 41.062124,
                "longitude": 28.974016,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 310,
                "name": "NEVTAŞ OTOMOTİV YATIRIMLARI VE ENERJİ A.Ş.",
                "shortName": "NEVTAŞ",
                "code": "98436",
                "mainCode": "98436",
                "address": "ÖRENCİK KÖYÜ, KAVACIK MEVKİ, KAVACIK KÜME EVLERİ No:41 ",
                "district": "MERKEZ",
                "city": "KASTAMONU",
                "latitude": 41.32526,
                "longitude": 33.77505,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 185,
                "name": "OFLAZLAR OTOM. MOB. DYN. TÜK. MALL. TEKS. KONF. GIDA İTH. MAD. TRZ. TAAH. EĞT. İNŞ. İHR. PAZ. TİC. SAN. LTD. ŞTİ.",
                "shortName": "OFLAZLAR",
                "code": "58104",
                "mainCode": "58104",
                "address": "ANKARA-ERZİNCAN KARAYOLU OTOGAR KARŞISI",
                "district": "MERKEZ",
                "city": "SİVAS",
                "latitude": 39.732,
                "longitude": 37.0178,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 230,
                "name": "OR-AY OTOM.İNŞ.TRZ.SAN.TİC.LTD.ŞTİ.",
                "shortName": "OR-AY",
                "code": "06416",
                "mainCode": "06701",
                "address": "İNÖNÜ M.F.SULTAN MEHMET BLV.9.KM.1730.SK.BATI PARK İŞ MRK.NO:3/B",
                "district": "YENİMAHALLE",
                "city": "ANKARA",
                "latitude": 39.945991,
                "longitude": 32.727895,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 298,
                "name": "ORDU MOT. ARÇ. SAN. VE TİC. A.Ş.",
                "shortName": "ORDU",
                "code": "45307",
                "mainCode": "45106",
                "address": "RAGIPBEY MAH. 21.SOK. NO:123",
                "district": "AKHİSAR",
                "city": "MANİSA",
                "latitude": 38.9281,
                "longitude": 27.8349,
                "isRenew": false,
                "isService": false,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 227,
                "name": "OTO PETROL SAN. VE TİC. A.Ş.",
                "shortName": "OTO PETROL",
                "code": "35408",
                "mainCode": "07101",
                "address": "ÇÜNÜR MAH. 102.CAD. NO:189 BÖLGE TRAFİK DENETLEME İSTASYONU BİTİŞİĞİ",
                "district": "MERKEZ",
                "city": "ISPARTA",
                "latitude": 37.803212,
                "longitude": 30.536663,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 233,
                "name": "POL-SA MOT. ARÇ. VE LASTİK SAN. TİC. LTD. ŞTİ.",
                "shortName": "POL-SA",
                "code": "19401",
                "mainCode": "19104",
                "address": "SAMSUN KARAYOLU 3.KM. NO:4",
                "district": "MERZİFON",
                "city": "AMASYA",
                "latitude": 40.870734,
                "longitude": 35.511864,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 215,
                "name": "SADIKOĞULLARI OTOM. PTR. TRZ. TİC. SAN. LTD. ŞTİ.",
                "shortName": "SADIKOĞULLARI",
                "code": "20106",
                "mainCode": "20106",
                "address": "AKÇEŞME MH. MENDERES BULVARI NO:150",
                "district": "GÜMÜŞLER",
                "city": "DENİZLİ",
                "latitude": 37.7998,
                "longitude": 29.0774,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 309,
                "name": "BİKAM SERVİS OTO ONARIM VE YEDEK PARÇA TİCARET SANAYİ ANONİM ŞİRKETİ",
                "shortName": "BİKAM",
                "code": "98450",
                "mainCode": "98450",
                "address": "MİMARSİNAN MAH. E5 LONDRA ASFALTI CAD. NO: 77 İÇ KAPI NO: 1 ",
                "district": "BÜYÜKÇEKMECE",
                "city": "İSTANBUL",
                "latitude": 41.01436,
                "longitude": 28.54954,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 312,
                "name": "BİKAS GIDA TİCARET ANONİM ŞİRKETİ",
                "shortName": "BİKAS",
                "code": "98456",
                "mainCode": "98456",
                "address": "ZAFER MAHALLESİ HARAMİDERE YOLU CADDESİ NO: 26/1",
                "district": "ESENYURT",
                "city": "İSTANBUL",
                "latitude": 41.015215,
                "longitude": 28.681702,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 160,
                "name": "CİHAN PET.ÜR.OTO.YURT İŞLT. İNŞ. TAAH. GIDA PAZ. TİC. SAN. LTD.ŞTİ.",
                "shortName": "CİHAN",
                "code": "06169",
                "mainCode": "06169",
                "address": "KONYA DEVLET YOLU ÜZERİ FEN LİSESİ KAVŞAĞI NO:208",
                "district": "ÇANKAYA",
                "city": "ANKARA",
                "latitude": 39.884203,
                "longitude": 32.81093,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 243,
                "name": "DAREN OTOM.İNŞ.SAN.VE TİC.LTD.ŞTİ.",
                "shortName": "DAREN",
                "code": "34374",
                "mainCode": "34143",
                "address": "EMEK MAH.FATİH SULTAN MEHMET CAD. NO:9",
                "district": "GEBZE",
                "city": "KOCAELİ",
                "latitude": 40.8016,
                "longitude": 29.3679,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 259,
                "name": "DEMİRELLER OTOM. SAN. VE TİC. AŞ.",
                "shortName": "DEMİRELLER",
                "code": "03102",
                "mainCode": "03102",
                "address": "YENİCE MAH. MAREŞAL FEVZİ ÇAKMAK BULVARI NO:55",
                "district": "MERKEZ",
                "city": "AFYONKARAHİSAR",
                "latitude": 38.759539,
                "longitude": 30.549807,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 172,
                "name": "DEMİRKOLLAR MOT. ARÇ. SAN. VE. TİC. A.Ş",
                "shortName": "DEMİRKOLLAR",
                "code": "98379",
                "mainCode": "98379",
                "address": "ALTUNİZADE MH. MAHİR İZ CD. NO:17",
                "district": "ÜSKÜDAR",
                "city": "İSTANBUL",
                "latitude": 41.0218,
                "longitude": 29.0404,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 208,
                "name": "DEMİRKOLLAR MOT. ARÇ. SAN. VE. TİC. A.Ş",
                "shortName": "DEMİRKOLLAR",
                "code": "98388",
                "mainCode": "98379",
                "address": "KISIKLI MAH. NATO YOLU BOSNA BULVARI NO:33",
                "district": "ÜSKÜDAR",
                "city": "İSTANBUL",
                "latitude": 41.028654,
                "longitude": 29.080188,
                "isRenew": false,
                "isService": false,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 273,
                "name": "DOĞUMAK OTOM. SAN. VE TİC. A.Ş",
                "shortName": "DOĞUMAK",
                "code": "25103",
                "mainCode": "25103",
                "address": "EDİP SOMUNOĞLU MH. TORTUM YOLU ÜZERİ",
                "district": "YAKUTİYE",
                "city": "ERZURUM",
                "latitude": 39.9297,
                "longitude": 41.2812,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 168,
                "name": "DİM-PA MEŞRUBAT GIDA PAZ.İTH. İHR. TİC.VE SAN.LTD.ŞTİ.",
                "shortName": "DİM-PA",
                "code": "65107",
                "mainCode": "65107",
                "address": "VAN-ERCİŞ KARAYOLU ÜZERİ BÖLGE TRAFİK YANI",
                "district": "TUŞBA",
                "city": "VAN",
                "latitude": 38.573713,
                "longitude": 43.305187,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 277,
                "name": "EDİRNE SERVİS VE OTOM.  A.Ş.",
                "shortName": "EDİRNE",
                "code": "98408",
                "mainCode": "98408",
                "address": "KOCA SINAN MAH. E5 KARAYOLU CAD. 97 Z2",
                "district": "MERKEZ",
                "city": "EDİRNE",
                "latitude": 41.636306,
                "longitude": 26.610404,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 296,
                "name": "ELİF OTOMOBİL SATIŞ VE BAKIM SAN. TİC. LTD. ŞTİ.",
                "shortName": "ELİF OTOM.",
                "code": "98418",
                "mainCode": "98418",
                "address": "BAHÇELİEVLER MAH KASTAMONU YOLU CAD. BOSTANBÜKÜ MEVKİİ NO:4/2",
                "district": "MERKEZ",
                "city": "KARABÜK",
                "latitude": 41.21659,
                "longitude": 32.67627,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 238,
                "name": "ERDEĞER MOT.ARÇ.VE İNŞ.SAN.VE TİC. A.Ş.",
                "shortName": "ERDEĞER",
                "code": "98393",
                "mainCode": "98393",
                "address": "ÇİFTLİK MAH. İZMİT KARAYOLU CAD. NO:356",
                "district": "ÇİFTLİKKÖY",
                "city": "YALOVA",
                "latitude": 40.67796,
                "longitude": 29.352416,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 204,
                "name": "ERMAT MOT. ARÇ. VE TARIM ÜRÜNL. SAN. TİC.  AŞ.",
                "shortName": "ERMAT",
                "code": "35112",
                "mainCode": "35112",
                "address": "BİNBAŞI REŞAT BEY MH. AKÇAY CD. NO:25/1",
                "district": "GAZİEMİR",
                "city": "İZMİR",
                "latitude": 38.3589,
                "longitude": 27.1363,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 256,
                "name": "ERMAT MOT. ARÇ. VE TARIM ÜRÜNL. SAN. TİC. AŞ.",
                "shortName": "ERMAT",
                "code": "35419",
                "mainCode": "35112",
                "address": "BALATÇIK MAH.ANADOLU CAD. NO:1273",
                "district": "ÇİĞLİ",
                "city": "İZMİR",
                "latitude": 38.50787,
                "longitude": 27.047003,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 166,
                "name": "ERNAZ SERVİS OTO PAZ. SAN. VE TİC. A.Ş.",
                "shortName": "ERNAZ SERVİS",
                "code": "54105",
                "mainCode": "54105",
                "address": "KÜPÇÜLER MAH. YENİ KARASU YOLU 1.KM. NO:70",
                "district": "ERENLER",
                "city": "SAKARYA",
                "latitude": 40.8128,
                "longitude": 30.4381,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 271,
                "name": "GÖÇMENTÜRK DYN. TK. ML. TİC. VE TRZ. LTD. ŞTİ.",
                "shortName": "GÖÇMENTÜRK",
                "code": "07110",
                "mainCode": "07110",
                "address": "ATATÜRK CAD. 8.SOK. NO:1",
                "district": "ALANYA",
                "city": "ANTALYA",
                "latitude": 36.529622,
                "longitude": 32.04829,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 191,
                "name": "GÜLPAR MOT. ARÇ. EV GEREÇLERİ TURİZM SEYAHAT NAKLİYE SAN. VE TİC. A.Ş.",
                "shortName": "GÜLPAR",
                "code": "38407",
                "mainCode": "38107",
                "address": "ORTA SANAYİ KEVSER CD. NO:13",
                "district": "MELİKGAZİ",
                "city": "KAYSERİ",
                "latitude": 38.7273,
                "longitude": 35.4525,
                "isRenew": false,
                "isService": false,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 153,
                "name": "ATILGAN MOTORLU ARAÇLAR SANAYİ TİCARET A.Ş.",
                "shortName": "ATILGAN İSTANBUL",
                "code": "98133",
                "mainCode": "98133",
                "address": "OSMANGAZİ MAH. BATTAL GAZİ CAD. NO:23",
                "district": "SANCAKTEPE",
                "city": "İSTANBUL",
                "latitude": 40.976519,
                "longitude": 29.244804,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 265,
                "name": "AZİZ ATİK OTOM. TİC. VE SAN. A.Ş.",
                "shortName": "AZİZ ATİK",
                "code": "55103",
                "mainCode": "55103",
                "address": "İSTİKLAL MAH. ATATÜRK BULVARI NO:205",
                "district": "TEKKEKÖY",
                "city": "SAMSUN",
                "latitude": 41.236366,
                "longitude": 36.412795,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 197,
                "name": "BADAY OTOM.NAK.İNŞ.TİC.LTD.ŞTİ.",
                "shortName": "BADAY",
                "code": "34436",
                "mainCode": "34701",
                "address": "FERHATPAŞA MAH. MAREŞAL FEVZİ ÇAKMAK CAD. \nNO:92-94",
                "district": "ATAŞEHİR",
                "city": "İSTANBUL",
                "latitude": 40.9784,
                "longitude": 29.1414,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 287,
                "name": "BAHAEDDİN ACAR",
                "shortName": "B.ACAR",
                "code": "56103",
                "mainCode": "56103",
                "address": "AFETEVLER MAH. HÜKÜMET CAD. NO:194",
                "district": "MERKEZ",
                "city": "SİİRT",
                "latitude": 37.57005,
                "longitude": 41.53326,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 216,
                "name": "BAYHAN MİM. OTOM. İNŞ. TKST.GIDA SAN. VE TİC. AŞ.",
                "shortName": "BAYHAN",
                "code": "24105",
                "mainCode": "24105",
                "address": "SİVAS KARAYOLU 2.KM.",
                "district": "MERKEZ",
                "city": "ERZİNCAN",
                "latitude": 39.762163,
                "longitude": 39.439549,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 173,
                "name": "BAYRAK OTOM. İNŞ.SAN.VE TİC.LTD.ŞTİ.",
                "shortName": "BAYRAK",
                "code": "98380",
                "mainCode": "34143",
                "address": "YALI MAH. D.100 YAN YOL CAD. NO:34",
                "district": "KARTAL",
                "city": "İSTANBUL",
                "latitude": 40.897468,
                "longitude": 29.224104,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 290,
                "name": "BAŞARAN OTOM.SAN.VE TİC.LTD.ŞTİ.",
                "shortName": "BAŞARAN",
                "code": "36401",
                "mainCode": "36401",
                "address": "Paşaçayır Mahallesi Rauf  Denktaş Caddesi No: 389",
                "district": "MERKEZ",
                "city": "KARS",
                "latitude": 40.566468,
                "longitude": 43.028274,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 205,
                "name": "BAŞTAŞ OTOM.SAN.VE TİC.A.Ş.",
                "shortName": "BAŞTAŞ",
                "code": "43104",
                "mainCode": "43104",
                "address": "ESKİŞEHİR YOLU 8.KM. ÇALCA MAHALLESİ",
                "district": "MERKEZ",
                "city": "KÜTAHYA",
                "latitude": 39.4802605,
                "longitude": 30.0354128,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 213,
                "name": "BOZTAŞIT MOT ARÇ. SAN VE TİC. LTD. ŞTİ.",
                "shortName": "BOZTAŞIT",
                "code": "02102",
                "mainCode": "02102",
                "address": "BAHÇELİEVLER MH. ATATÜRK BULVARI NO:340",
                "district": "MERKEZ",
                "city": "ADIYAMAN",
                "latitude": 37.762551,
                "longitude": 38.293416,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 222,
                "name": "BUHARİ OTOM. MAM. PAZ. İMAL. SAN. VE TİC. A.Ş.",
                "shortName": "BUHARİ",
                "code": "59103",
                "mainCode": "59103",
                "address": "ÖNERLER MÜCEVİR ALAN İSTANBUL CADDESİ NO35/A (Digital NO 2551944073)",
                "district": "ÇORLU",
                "city": "TEKİRDAĞ",
                "latitude": 41.14338,
                "longitude": 27.861365,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 186,
                "name": "BUHARİ OTOM. MAM. PAZ. İMAL. SAN. VE TİC. A.Ş.",
                "shortName": "BUHARİ",
                "code": "59401",
                "mainCode": "59103",
                "address": "İSTANBUL YOLU ÜZERİ 7.KM KÖSE İLYAS KÖYÜ MEVKİİ",
                "district": "MERKEZ",
                "city": "TEKİRDAĞ",
                "latitude": 40.9896,
                "longitude": 27.5952,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 228,
                "name": "BİRLİK OTO MOT. ARÇ. SAN. VE TİC. LTD. ŞTİ.",
                "shortName": "BİRLİK",
                "code": "34335",
                "mainCode": "98131",
                "address": "AYAZMA YOLU DEMET İŞ MERKEZİ NO:33",
                "district": "KAĞITHANE",
                "city": "İSTANBUL",
                "latitude": 41.08455329602394,
                "longitude": 28.98465007895283,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 156,
                "name": "CEM YEDEK PARÇA OTOM.GIDA TRZ. SAN. TİC.LTD.ŞTİ.",
                "shortName": "CEM",
                "code": "35414",
                "mainCode": "35112",
                "address": "MERİÇ MAH. FATİH CAD. NO:107",
                "district": "BORNOVA",
                "city": "İZMİR",
                "latitude": 38.4372,
                "longitude": 27.181,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 178,
                "name": "COŞKUN ALTINYAKIT SAN. VE TİC. A.Ş.",
                "shortName": "COŞKUN ALTINYAKIT",
                "code": "06401",
                "mainCode": "06701",
                "address": "BAHÇEKAPI MAH.2474 SOK. NO:21",
                "district": "ETİMESGUT",
                "city": "ANKARA",
                "latitude": 39.940791,
                "longitude": 32.716884,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 242,
                "name": "ERNAZ OTOM. SAN. TİC. VE PAZ. A.Ş.",
                "shortName": "ERNAZ",
                "code": "41106",
                "mainCode": "41106",
                "address": "KÖRFEZ MH. SEFA SİRMEN BULVARI ESKİ GÖLCÜK YOLU OUTLET CENTER KARŞISI",
                "district": "İZMİT",
                "city": "KOCAELİ",
                "latitude": 40.7613,
                "longitude": 29.9411,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 266,
                "name": "SARAR OTOM. PETROL ÜRÜNLERİ TURİZM TİC. SAN. A.Ş.",
                "shortName": "SARAR",
                "code": "98383",
                "mainCode": "98383",
                "address": "BATIKENT MAH. BADEMLİYOL SOK. NO:101-101/A",
                "district": "TEPEBAŞI",
                "city": "ESKİŞEHİR",
                "latitude": 39.799447,
                "longitude": 30.435138,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 272,
                "name": "SARUHAN MOT. ARÇ. TAŞ. İNŞ. TİC. VE SAN. AŞ.",
                "shortName": "SARUHAN",
                "code": "17104",
                "mainCode": "17104",
                "address": "KEPEZ MAH. İZMİR CAD.",
                "district": "MERKEZ",
                "city": "ÇANAKKALE",
                "latitude": 40.1532,
                "longitude": 26.4153,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 232,
                "name": "SOMTAŞ SEVERLER OTO  MOT. ARÇ. TİC. A.Ş.",
                "shortName": "SOMTAŞ",
                "code": "10101",
                "mainCode": "10101",
                "address": "YENİ MAH. GÖNEN YOLU 2.KM.",
                "district": "BANDIRMA",
                "city": "BALIKESİR",
                "latitude": 40.339275,
                "longitude": 27.950447,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 225,
                "name": "TARANDİR OTOM.MOT.ARAC A.Ş.",
                "shortName": "TARANDİR",
                "code": "98382",
                "mainCode": "98382",
                "address": "KONAK MAH. SİLOPİ YOLU 3.KM.",
                "district": "CİZRE",
                "city": "ŞIRNAK",
                "latitude": 37.324023,
                "longitude": 42.217032,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 254,
                "name": "GÖZDEM OTOM. LTD. ŞTİ.",
                "shortName": "GÖZDEM",
                "code": "98362",
                "mainCode": "34124",
                "address": "YENİSAHRA MAH. ORDU CAD. MUHTAR AHMET AYDIN SOK. NO:2",
                "district": "ATAŞEHİR",
                "city": "İSTANBUL",
                "latitude": 40.994212,
                "longitude": 29.090718,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 281,
                "name": "GÜRSES MOTORLU ARAÇLAR ALIM SATIM TİCARET A.Ş.",
                "shortName": "GÜRSES MOT.ARÇ.",
                "code": "98409",
                "mainCode": "98409",
                "address": "BASIN EKSPRES YOLU CEMAL ULUSOY CAD. NO:9 YENIBOSNA",
                "district": "BAHÇELİEVLER",
                "city": "İSTANBUL",
                "latitude": 41.013246,
                "longitude": 28.811555,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 234,
                "name": "TURGUT ÖZKAYA SAN. VE TİC. LTD. ŞTİ.",
                "shortName": "T.ÖZKAYA",
                "code": "23101",
                "mainCode": "23101",
                "address": "ELAZIĞ-DİYARBAKIR-BİNGÖL KAVŞAĞI KEKLİKTEPE MEVKİİ",
                "district": "MERKEZ",
                "city": "ELAZIĞ",
                "latitude": 38.636391,
                "longitude": 39.257603,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 209,
                "name": "TİRE AKÇİNLER MOT.ARÇ.İNŞ.SAN.VE TİC.LTD.ŞTİ.",
                "shortName": "TİRE AKÇİNLER",
                "code": "35413",
                "mainCode": "35112",
                "address": "İBNİ MELEK MAH. FATİH SULTAN MEHMET BLV. NO:1",
                "district": "TİRE",
                "city": "İZMİR",
                "latitude": 38.108328,
                "longitude": 27.711449,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 183,
                "name": "URMA OTOM.SAN. VE TİC. A.Ş.",
                "shortName": "URMA",
                "code": "44105",
                "mainCode": "44105",
                "address": "1. OSB MH. HAVALANI YOLU ÜZERİ 3. KM.",
                "district": "YEŞİLYURT",
                "city": "MALATYA",
                "latitude": 38.3633,
                "longitude": 38.1823,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 244,
                "name": "UZMAN OTOM. SAN. VE DIŞ TİC. LTD. ŞTİ.",
                "shortName": "UZMAN",
                "code": "34420",
                "mainCode": "34701",
                "address": "FERHATPAŞA MAH. YEDİTEPE CAD. NO:122-123-124",
                "district": "ATAŞEHİR",
                "city": "İSTANBUL",
                "latitude": 40.9882,
                "longitude": 29.168,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 192,
                "name": "UZUNLAR OTOM. ZAHİRE SAN. VE TİC. LTD. ŞTİ.",
                "shortName": "UZUNLAR",
                "code": "39103",
                "mainCode": "39103",
                "address": "İSTANBUL YOLU ÜZERİ 1.KM.",
                "district": "LÜLEBURGAZ",
                "city": "KIRKLARELİ",
                "latitude": 41.3979,
                "longitude": 27.3776,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 241,
                "name": "UZUNLAR OTOM. ZAHİRE SAN. VE TİC. LTD. ŞTİ.",
                "shortName": "UZUNLAR",
                "code": "39303",
                "mainCode": "39103",
                "address": "KİPA AVM YANI KAVAKLI YOLU ÜZERİ",
                "district": "MERKEZ",
                "city": "KIRKLARELİ",
                "latitude": 41.7218,
                "longitude": 27.2169,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 307,
                "name": "VİSİON YEDEK PARÇA OTOMOTİV SANAYİ VE TİCARET ANONİM ŞİRKETİ",
                "shortName": "VİZYON DÜZCE",
                "code": "98445",
                "mainCode": "98445",
                "address": "ÜÇKÖPRÜ KÖYÜ YENİDOĞAN MEVKİİ 114.SOK. NO:72",
                "district": "KAYNAŞLI",
                "city": "DÜZCE",
                "latitude": 40.7998,
                "longitude": 31.2434,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 155,
                "name": "YAŞAR MOT. ARÇ. YED. PRÇ. SAN. TİC. LTD. ŞTİ.",
                "shortName": "YAŞAR",
                "code": "35412",
                "mainCode": "35701",
                "address": "KEMALPAŞA OSB MH. İZMİR ANKARA ASFALTI CD. NO:37",
                "district": "KEMALPAŞA",
                "city": "İZMİR",
                "latitude": 38.463606,
                "longitude": 27.347453,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 165,
                "name": "ÇELİK MOT. ARÇ. SAN. VE TİC. AŞ.",
                "shortName": "ÇELİK",
                "code": "42311",
                "mainCode": "42111",
                "address": "D300 KARAYOLU ÜZERİ NO:1",
                "district": "AKŞEHİR",
                "city": "KONYA",
                "latitude": 38.22177,
                "longitude": 31.26196,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 260,
                "name": "ÇELİK OTO RAMAZAN ÇELİK KOLL. ŞTİ.",
                "shortName": "ÇELİK OTO",
                "code": "06165",
                "mainCode": "06701",
                "address": "BAHÇEKAPI MAH. SANAYİ BULVARI NO:22-51 ŞAŞMAZ",
                "district": "ETİMESGUT",
                "city": "ANKARA",
                "latitude": 39.938268,
                "longitude": 32.712752,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 245,
                "name": "ÇETAŞ OTOM. AKARYAKIT TİC. A.Ş.",
                "shortName": "ÇETAŞ",
                "code": "34158",
                "mainCode": "34158",
                "address": "GÖZTEPE MH. İNÖNÜ CD. NO:19  MAHMUTBEY",
                "district": "BAĞCILAR",
                "city": "İSTANBUL",
                "latitude": 41.0608,
                "longitude": 28.8321,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 203,
                "name": "ÇETAŞ OTOM. AKARYAKIT TİC. A.Ş.",
                "shortName": "ÇETAŞ",
                "code": "34443",
                "mainCode": "34158",
                "address": "CUMHURİYET MH. DERSAADET CAD. NO:2",
                "district": "SULTANGAZİ",
                "city": "İSTANBUL",
                "latitude": 41.09092,
                "longitude": 28.885119,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 279,
                "name": "ÇETAŞ OTOM. AKARYAKIT TİC. A.Ş.",
                "shortName": "ÇETAŞ",
                "code": "98423",
                "mainCode": "34158",
                "address": "Aşık Veysel mah.Atatürk Bulvarı No:16 Bahçeşehir",
                "district": "ESENYURT",
                "city": "İSTANBUL",
                "latitude": 41.0631593,
                "longitude": 28.6683769,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 294,
                "name": "ÇETAŞ İZMİR OTOMOTİV A.Ş.",
                "shortName": "ÇETAŞ İZMİR",
                "code": "98428",
                "mainCode": "98428",
                "address": "DOĞANLAR MAH. ANKARA CAD. 210-A",
                "district": "BORNOVA",
                "city": "İZMİR",
                "latitude": 38.45616,
                "longitude": 27.25389,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 187,
                "name": "ÇİFTÇİOĞLU OTOM.SAN.TİC.LTD.ŞTİ.",
                "shortName": "ÇİFTÇİOĞLU",
                "code": "64103",
                "mainCode": "64103",
                "address": "FEVZİ ÇAKMAK MAH. GAZİ BULVARI NO :100/A",
                "district": "MERKEZ",
                "city": "UŞAK",
                "latitude": 38.6752,
                "longitude": 29.4329,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 175,
                "name": "ÖZ-ÜÇLER OTOM. SAN.VE TİC .LTD. ŞTİ.",
                "shortName": "ÖZ-ÜÇLER",
                "code": "34334",
                "mainCode": "98409",
                "address": "KARTALTEPE MAH. D100/E-5 KARAYOLU C BLOK NO:20 SEFAKÖY",
                "district": "KÜÇÜKÇEKMECE",
                "city": "İSTANBUL",
                "latitude": 41.000889442164095,
                "longitude": 28.803353649066924,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 169,
                "name": "ÖZERLER OTOM. VE PTR. ÜRNL. PAZ. SAN. VE TİC. A.Ş.",
                "shortName": "ÖZERLER",
                "code": "67104",
                "mainCode": "67104",
                "address": "KEPEZ MH. PROF. MUAMMER AKSOY CD. NO:10",
                "district": "KDZ.EREĞLİ",
                "city": "ZONGULDAK",
                "latitude": 41.264999,
                "longitude": 31.475986,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 292,
                "name": "ÖZERLER OTOM. VE PTR. ÜRNL. PAZ. SAN. VE TİC. A.Ş.",
                "shortName": "ÖZERLER",
                "code": "74201",
                "mainCode": "67104",
                "address": "ÇATMACA MEVKİİ KAVCALLAR CD. ANARLİN SİT. A1/BLOK  NO:1",
                "district": "MERKEZ",
                "city": "BARTIN",
                "latitude": 41.6226,
                "longitude": 32.3146,
                "isRenew": false,
                "isService": false,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 179,
                "name": "ÖZKILIÇ MOT. ARÇ. TEKSTİL İNŞAAT SAN.TİC.LTD.ŞTİ.",
                "shortName": "ÖZKILIÇ",
                "code": "21106",
                "mainCode": "21106",
                "address": "BAĞCILAR MAH. ŞANLIURFA KARAYOLU 1107 SOK.",
                "district": "BAĞLAR",
                "city": "DİYARBAKIR",
                "latitude": 37.928736,
                "longitude": 40.178855,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 251,
                "name": "İMAM KAYALIOĞULLARI OTOM. TİC. SAN. A.Ş.",
                "shortName": "İ.KAYALIOĞULLARI",
                "code": "27103",
                "mainCode": "27103",
                "address": "MÜCAHİTLER MAH. SANİ KONUKOĞLU BULV. NO:104",
                "district": "ŞEHİTKAMİL",
                "city": "GAZİANTEP",
                "latitude": 37.076202,
                "longitude": 37.370834,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 180,
                "name": "İMAM KAYALIOĞULLARI OTOM. TİC. SAN. A.Ş.",
                "shortName": "İ.KAYALIOĞULLARI",
                "code": "27106",
                "mainCode": "27103",
                "address": "BİNEVLER MH. ÜNİVERSİTE BULVARI NO:146",
                "district": "ŞAHİNBEY",
                "city": "GAZİANTEP",
                "latitude": 37.053955,
                "longitude": 37.337547,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 194,
                "name": "İNCİ OTOM. SAN. TİC. LTD. ŞTİ.",
                "shortName": "İNCİ",
                "code": "34414",
                "mainCode": "34701",
                "address": "EVLİYA ÇELEBİ CD. ANBAR ARKASI SK. NO:10/A  KASIMPAŞA",
                "district": "BEYOĞLU",
                "city": "İSTANBUL",
                "latitude": 41.0295,
                "longitude": 28.9685,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 295,
                "name": "İSA-UFUK OTOMOTİV ZİR. TAR. PAZ. SAN. VE TİC. LTD. STİ.",
                "shortName": "İSA-UFUK",
                "code": "98381",
                "mainCode": "33109",
                "address": "BAHÇE MAH. SANAYİ SİTESİ KARŞISI ALPARSLAN TÜRKEŞ BULVARI NO:15/A",
                "district": "ANAMUR",
                "city": "MERSİN",
                "latitude": 36.07515,
                "longitude": 32.838539,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 313,
                "name": "İZMİR ŞUBE PINARBAŞI",
                "shortName": "İZMİR ŞUBE PINARBAŞI",
                "code": "98449",
                "mainCode": "35701",
                "address": "KEMALPAŞA MH. KEMALPAŞA CD. 7401 SK. NO:3 ",
                "district": "BORNOVA",
                "city": "İZMİR",
                "latitude": 38.437871,
                "longitude": 27.245721,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 274,
                "name": "NEVZAT ŞAHİN MOTORLU ARAÇLAR LTD.ŞTİ",
                "shortName": "NEVZAT ŞAHİN",
                "code": "31102",
                "mainCode": "31102",
                "address": "ANTAKYA-İSKENDERUN KARAYOLU ÜZERİ 7.KM",
                "district": "MERKEZ",
                "city": "HATAY",
                "latitude": 36.278595,
                "longitude": 36.191177,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 275,
                "name": "NEVZAT ŞAHİN MOTORLU ARAÇLAR LTD.ŞTİ",
                "shortName": "NEVZAT ŞAHİN",
                "code": "31301",
                "mainCode": "31102",
                "address": "ANTAKYA YOLU ÜZERİ 5.KM.",
                "district": "İSKENDERUN",
                "city": "HATAY",
                "latitude": 36.5909,
                "longitude": 36.1782,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 253,
                "name": "ORDU MOT. ARÇ. SAN. VE TİC. A.Ş.",
                "shortName": "ORDU",
                "code": "45106",
                "mainCode": "45106",
                "address": "2.ANAFARTALAR MH. MİMARSİNAN BULVARI 1527 SOK. 18/A",
                "district": "ŞEHZADELER",
                "city": "MANİSA",
                "latitude": 38.626,
                "longitude": 27.4356,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 206,
                "name": "ORDU MOT. ARÇ. SAN. VE TİC. A.Ş.",
                "shortName": "ORDU",
                "code": "45306",
                "mainCode": "45106",
                "address": "SUBAŞI MH. ATATÜRK BULVARI NO:304",
                "district": "TURGUTLU",
                "city": "MANİSA",
                "latitude": 38.4953,
                "longitude": 27.705,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 193,
                "name": "ORSA OTO",
                "shortName": "ORSA",
                "code": "34375",
                "mainCode": "34143",
                "address": "AYDINTEPE MH. AYDINLI YOLU UZERI NO.25 B.2  TUZLA OTO SAN.SIT.YANI",
                "district": "TUZLA",
                "city": "İSTANBUL",
                "latitude": 40.850794,
                "longitude": 29.303854,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 154,
                "name": "OTONOVA OTOMOTİV SAN.TİC.A.Ş.",
                "shortName": "OTONOVA",
                "code": "98389",
                "mainCode": "98389",
                "address": "NECİP FAZIL MAH.HAMZA YERLİKAYA BULVARI MAZHAR OSMAN SK.NO:74",
                "district": "ÜMRANİYE",
                "city": "İSTANBUL",
                "latitude": 41.028326,
                "longitude": 29.171742,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 255,
                "name": "REN-SER  OTOM. İÇ VE DIŞ TİC. LTD. ŞTİ.",
                "shortName": "REN-SER",
                "code": "35409",
                "mainCode": "35112",
                "address": "YENİKALE MAH.MUSTAFA KEMAL SAHİL BULV. NO:12",
                "district": "NARLIDERE",
                "city": "İZMİR",
                "latitude": 38.3967,
                "longitude": 27.0191,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 219,
                "name": "RENOTO SAN. TİC. A.Ş.",
                "shortName": "RENOTO",
                "code": "35104",
                "mainCode": "35701",
                "address": "MERİÇ MAH.SANAT CAD.5627 SOK.NO:9/A",
                "district": "BORNOVA",
                "city": "İZMİR",
                "latitude": 38.427059,
                "longitude": 27.186966,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 211,
                "name": "RENSER MOT.ARÇ.SAN.VE TİC.LTD.ŞTİ.",
                "shortName": "RENSER",
                "code": "34437",
                "mainCode": "34158",
                "address": "ZİYA GÖKALP MAH. İKİTELLİ O.S.B. ATATÜRK BLV. NO:56/B",
                "district": "BAŞAKŞEHİR",
                "city": "İSTANBUL",
                "latitude": 41.0788,
                "longitude": 28.8081,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 250,
                "name": "SİMA OTOM. SAN. TİC. A.Ş.",
                "shortName": "SİMA",
                "code": "19104",
                "mainCode": "19104",
                "address": "ANKARA YOLU 4.KM NO:168",
                "district": "MERKEZ",
                "city": "ÇORUM",
                "latitude": 40.5361,
                "longitude": 34.9339,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 229,
                "name": "SİSTEM 2 OTOM.AKARYAKIT TAŞM. TRZ. İNŞ. SAN.VE TİC.LTD.ŞTİ.",
                "shortName": "SİSTEM 2",
                "code": "06322",
                "mainCode": "06701",
                "address": "ÜMİTKÖY  MAH. MEKSİKA CAD.56/2-A",
                "district": "ÇANKAYA",
                "city": "ANKARA",
                "latitude": 39.902279,
                "longitude": 32.695419,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 286,
                "name": "TAN OTO MOT.ARÇ. TAŞ. VE İNŞ. LTD.ŞTİ.",
                "shortName": "TAN OTO",
                "code": "98385",
                "mainCode": "98385",
                "address": "Çamlıca Mahallesi 145 Sokak No: 11 Gimat",
                "district": "YENİMAHALLE",
                "city": "ANKARA",
                "latitude": 39.958679,
                "longitude": 32.778752,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 171,
                "name": "GÜVEN ALTAN MOT. ARÇ. TİC. LTD. ŞTİ.",
                "shortName": "GÜVEN ALTAN",
                "code": "98102",
                "mainCode": "98102",
                "address": "BAĞLARBAŞI MH. SAKARYA SK. NO:10-13",
                "district": "MALTEPE",
                "city": "İSTANBUL",
                "latitude": 40.9324,
                "longitude": 29.1421,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 207,
                "name": "GİRAY TURİZM PTR. ÜRNL. PAZ. VE TİC. LTD. ŞTİ.",
                "shortName": "GİRAY",
                "code": "98366",
                "mainCode": "98366",
                "address": "GENÇOSMAN MH. 2.SK. NO:1",
                "district": "DULKADİROĞLU",
                "city": "K.MARAŞ",
                "latitude": 37.556992,
                "longitude": 36.958248,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 252,
                "name": "HEDEF OTOM. TİC. SAN. A.Ş.",
                "shortName": "HEDEF",
                "code": "34116",
                "mainCode": "34116",
                "address": "KAZLIÇEŞME MAH. ABAY CAD. NO:84",
                "district": "ZEYTİNBURNU",
                "city": "İSTANBUL",
                "latitude": 40.9822,
                "longitude": 28.8955,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 270,
                "name": "HEDEF OTOM. TİC. SAN. A.Ş.",
                "shortName": "HEDEF",
                "code": "34431",
                "mainCode": "34116",
                "address": "ŞENLİKKÖY MAH. E-5 ÜZERİ YEŞİLOVA OTOBÜS DURAĞI NO:4A",
                "district": "BAKIRKÖY",
                "city": "İSTANBUL",
                "latitude": 40.9858,
                "longitude": 28.7867,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 188,
                "name": "HEKİMOĞLU MOT.ARÇ.TEKSTİL GIDA VE HAYVANCILIK SAN.TİC.LTD.ŞTİ.",
                "shortName": "HEKİMOĞLU",
                "code": "66103",
                "mainCode": "19104",
                "address": "AYDINLIKEVLER MH. ANKARA CAD.NO:2",
                "district": "SORGUN",
                "city": "YOZGAT",
                "latitude": 39.8119,
                "longitude": 35.1883,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 299,
                "name": "HSC OTOM. TRZ.İNŞ.SAN. VE TİC. A.Ş.",
                "shortName": "HSC OTOM.",
                "code": "98413",
                "mainCode": "98413",
                "address": "SANCAK MAH. RİZE DEVLET YOLU ÜZERİ KAŞÜSTÜ BELDESİ",
                "district": "YOMRA",
                "city": "TRABZON",
                "latitude": 40.9314,
                "longitude": 39.8458,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 289,
                "name": "KAHYAOĞULLARI MOT.ARÇ. A.Ş.",
                "shortName": "KAHYAOĞULLARI",
                "code": "98404",
                "mainCode": "98404",
                "address": "KUYULU MAH. KAVAK MÜCAVİR SOK. NO:297",
                "district": "EFELER",
                "city": "AYDIN",
                "latitude": 37.8484,
                "longitude": 27.7867,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 303,
                "name": "KAHYAOĞULLARI MOT.ARÇ. A.Ş.",
                "shortName": "KAHYAOĞULLARI",
                "code": "98405",
                "mainCode": "98404",
                "address": "YALANSU MAH. SÜLEYMAN DEMİREL BULVARI NO:175",
                "district": "KUŞADASI",
                "city": "AYDIN",
                "latitude": 37.8406,
                "longitude": 27.2595,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 239,
                "name": "KANİ MOT. ARÇ. LTD. ŞTİ.",
                "shortName": "KANİ",
                "code": "35406",
                "mainCode": "35701",
                "address": "KAZIM DİRİK MAH. 378.SOK. NO:4",
                "district": "BORNOVA",
                "city": "İZMİR",
                "latitude": 38.4449,
                "longitude": 27.196,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 284,
                "name": "KAR MABOTO OTOMOTİV GIDA VE İNŞAAT SANAYİ TİCARET LTD.ŞTİ.",
                "shortName": "KAR MABOTO",
                "code": "98424",
                "mainCode": "42111",
                "address": "HAMİDİYE MAHALLESİ SANAYİ CADDESİ NO:7",
                "district": "MERKEZ",
                "city": "KARAMAN",
                "latitude": 37.182119,
                "longitude": 33.236544,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 196,
                "name": "KARAKUŞLAR OTOM.SAN.VE TİC.LTD.ŞTİ.",
                "shortName": "KARAKUŞLAR",
                "code": "34434",
                "mainCode": "34116",
                "address": "KARAKUŞLAR İŞ MRK. ESKİ LONDRA ASFALTI NO:111",
                "district": "GÜNGÖREN",
                "city": "İSTANBUL",
                "latitude": 41.0177,
                "longitude": 28.8811,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 237,
                "name": "KAREN SERVİS HİZM.VE NAKİL VAS. TİC. LTD. ŞTİ.",
                "shortName": "KAREN SERVİS",
                "code": "41401",
                "mainCode": "34143",
                "address": "CUMHURİYET MAH. MUHSİN YAZICIOĞLU CAD. NO:132 ŞEKERPINAR-ÇAYIROVA",
                "district": "GEBZE",
                "city": "KOCAELİ",
                "latitude": 40.8688,
                "longitude": 29.3764,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 162,
                "name": "KEMAL TEPRETOĞULLARI OTOM. SAN. VE TİC. A.Ş.",
                "shortName": "K.TEPRETOĞULLARI",
                "code": "34124",
                "mainCode": "34124",
                "address": "ACIBADEM MAH. BAĞ SOK.NO:19",
                "district": "KADIKÖY",
                "city": "İSTANBUL",
                "latitude": 41.002682,
                "longitude": 29.036529,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 301,
                "name": "KEMAL TEPRETOĞULLARI OTOM. SAN. VE TİC. A.Ş.",
                "shortName": "K.TEPRETOĞULLARI",
                "code": "34410",
                "mainCode": "34124",
                "address": "MUSTAFA KEMAL MAH 30004.SOK.NO:26",
                "district": "ATAŞEHİR",
                "city": "İSTANBUL",
                "latitude": 40.999311,
                "longitude": 29.093904,
                "isRenew": false,
                "isService": false,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 189,
                "name": "KIYI OTOM.SAN.VE TİC.AŞ.",
                "shortName": "KIYI",
                "code": "98130",
                "mainCode": "98130",
                "address": "SANAYİ MAH. DEDEPAŞA CAD. NO:52/1",
                "district": "PENDİK",
                "city": "İSTANBUL",
                "latitude": 40.9307,
                "longitude": 29.3364,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 161,
                "name": "KOÇASLANLAR MOT.ARÇ.ARAÇ KR.PET. ÜRNL. LAS.SAN.VE TİC. LTD. ŞTİ.",
                "shortName": "KOÇASLANLAR",
                "code": "16116",
                "mainCode": "16116",
                "address": "SÜLEYMANİYE MAH. ANKARA-BURSA KARAYOLU 2.KM.",
                "district": "İNEGÖL",
                "city": "BURSA",
                "latitude": 40.090032,
                "longitude": 29.503604,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 220,
                "name": "KUTAY MOT.ARÇ. TRZ. TAŞIMACILIK, İNŞAAT, AKARYAKIT SAN.TİC.AŞ.",
                "shortName": "KUTAY",
                "code": "48108",
                "mainCode": "48108",
                "address": "MUĞLA-AYDIN KARAYOLU 10.KM  SALİHPAŞALAR MEVKİİ",
                "district": "MENTEŞE",
                "city": "MUĞLA",
                "latitude": 37.2122,
                "longitude": 28.3659,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 263,
                "name": "KÖY OTOM. İTH. ve İHR. LTD. ŞTİ.",
                "shortName": "KÖY",
                "code": "52104",
                "mainCode": "52104",
                "address": "CUMHURİYET MAH. MUSTAFA KEMAL BLV. NO:56",
                "district": "ALTINORDU",
                "city": "ORDU",
                "latitude": 40.98,
                "longitude": 37.8942,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 231,
                "name": "MAİS A.Ş. ANKARA ŞUBE MÜDÜRLÜĞÜ",
                "shortName": "ANKARA ŞUBE",
                "code": "06701",
                "mainCode": "06701",
                "address": "MUSTAFA KEMAL MAH. 2079 SOKAK NO:5",
                "district": "ÇANKAYA",
                "city": "ANKARA",
                "latitude": 39.910495,
                "longitude": 32.743526,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 202,
                "name": "MAİS A.Ş. BURSA ŞUBE MÜDÜRLÜĞÜ",
                "shortName": "BURSA ŞUBE",
                "code": "16701",
                "mainCode": "16701",
                "address": "ATAEVLER İZMİR YOLU NO:226",
                "district": "NİLÜFER",
                "city": "BURSA",
                "latitude": 40.214212,
                "longitude": 28.953714,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 236,
                "name": "MAİS A.Ş. İSTANBUL ŞUBE MÜDÜRLÜĞÜ",
                "shortName": "İSTANBUL ŞUBE",
                "code": "34701",
                "mainCode": "34701",
                "address": "SARIYER CAD.(İSTİNYE) NO:68",
                "district": "SARIYER",
                "city": "İSTANBUL",
                "latitude": 41.120187,
                "longitude": 29.048186,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": true
            },
            {
                "id": 240,
                "name": "MAİS A.Ş. İZMİR ŞUBE MÜDÜRLÜĞÜ",
                "shortName": "İZMİR ŞUBE",
                "code": "35701",
                "mainCode": "35701",
                "address": "KAZIM DİRİK MAH. ÜNİVERSİTE CD. NO:41",
                "district": "BORNOVA",
                "city": "İZMİR",
                "latitude": 38.4542,
                "longitude": 27.2003,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 170,
                "name": "YENİLLER OTOM.SAN. VE TİC. LTD. ŞTİ.",
                "shortName": "YENİLLER",
                "code": "68301",
                "mainCode": "42111",
                "address": "ÇİFTLİK MAH. E90 BULVARI 1.KM.",
                "district": "MERKEZ",
                "city": "AKSARAY",
                "latitude": 38.396022,
                "longitude": 33.986916,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 224,
                "name": "YILDIZLAR OTOM.PETROL TRZ.VE TİC.LTD.ŞTİ.",
                "shortName": "YILDIZLAR",
                "code": "76101",
                "mainCode": "76101",
                "address": "14 KASIM MAH. İLHAM ALİYEV CAD. NO:296",
                "district": "MERKEZ",
                "city": "IĞDIR",
                "latitude": 39.936732,
                "longitude": 44.075035,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 195,
                "name": "YURT OTOM. SAN. VE TİC. LTD. ŞTİ.",
                "shortName": "YURT",
                "code": "34423",
                "mainCode": "34701",
                "address": "FİRUZKÖY BULVARI NO:106/A",
                "district": "AVCILAR",
                "city": "İSTANBUL",
                "latitude": 41.0024,
                "longitude": 28.7139,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 159,
                "name": "YUSUF BAYSAL OTOM. SAN. VE TİC. A.Ş.",
                "shortName": "Y.BAYSAL",
                "code": "01104",
                "mainCode": "01104",
                "address": "ADANA-CEYHAN KARAYOLU 6.KM",
                "district": "YÜREĞİR",
                "city": "ADANA",
                "latitude": 36.984386,
                "longitude": 35.382008,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 247,
                "name": "YUSUF BAYSAL OTOM. SAN. VE TİC. A.Ş.",
                "shortName": "Y.BAYSAL",
                "code": "01301",
                "mainCode": "01104",
                "address": "ŞİRİNEVLER MH.MUSA ŞAHİN BLV.NO:1",
                "district": "MERKEZ",
                "city": "OSMANİYE",
                "latitude": 37.0679,
                "longitude": 36.2341,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 199,
                "name": "YUSUF BAYSAL OTOM. SAN. VE TİC. A.Ş.",
                "shortName": "Y.BAYSAL",
                "code": "01402",
                "mainCode": "01104",
                "address": "VARSAKLAR MAH. ADANA CAD. NO:215/A",
                "district": "KOZAN",
                "city": "ADANA",
                "latitude": 37.436379,
                "longitude": 35.794143,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 200,
                "name": "ZAMANLAR OTOM. TİC.LTD.ŞTİ.",
                "shortName": "ZAMANLAR",
                "code": "07101",
                "mainCode": "07101",
                "address": "ALTINOVA SİNAN MH. SERİK CD. NO:77",
                "district": "KEPEZ",
                "city": "ANTALYA",
                "latitude": 36.918127,
                "longitude": 30.782855,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 283,
                "name": "ZAMANLAR OTOM. TİC.LTD.ŞTİ.",
                "shortName": "ZAMANLAR",
                "code": "32202",
                "mainCode": "07101",
                "address": "ÇÜNÜR MAH. 102.CAD. NO:189 BÖLGE TRAFİK DENETLEME İSTASYONU BİTİŞİĞİ",
                "district": "MERKEZ",
                "city": "ISPARTA",
                "latitude": 37.776,
                "longitude": 30.5493,
                "isRenew": false,
                "isService": false,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 267,
                "name": "ZAMANLAR OTOM. TİC.LTD.ŞTİ.",
                "shortName": "ZAMANLAR",
                "code": "98390",
                "mainCode": "07101",
                "address": "GÜVENLİK MH. 275 SK. NO:31 ÇALLI",
                "district": "MURATPAŞA",
                "city": "ANTALYA",
                "latitude": 36.903275,
                "longitude": 30.683861,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 176,
                "name": "ÇALIŞIR MOT. ARÇ. VE TİC. LTD. ŞTİ.",
                "shortName": "ÇALIŞIR",
                "code": "34343",
                "mainCode": "34701",
                "address": "ZÜMRÜTEVLER MAH.ATATÜRK CAD.NO:34",
                "district": "MALTEPE",
                "city": "İSTANBUL",
                "latitude": 40.9334,
                "longitude": 29.1405,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 217,
                "name": "ÇAYAN OTOM. İNŞ. VE TİC. LTD. ŞTİ.",
                "shortName": "ÇAYAN",
                "code": "33106",
                "mainCode": "33106",
                "address": "YUNUSEMRE MH. NATO YOLU KAVŞAĞI NO:74 YENİHAL KARŞISI",
                "district": "TARSUS",
                "city": "MERSİN",
                "latitude": 36.904213,
                "longitude": 34.873821,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 268,
                "name": "ÇAĞLAYANLAR OTOM. TİC. VE SAN. LTD. ŞTİ.",
                "shortName": "ÇAĞLAYANLAR",
                "code": "40104",
                "mainCode": "40104",
                "address": "KINDAM MAH. ANKARA KAYSERİ CAD.NO:8",
                "district": "MERKEZ",
                "city": "KIRŞEHİR",
                "latitude": 39.07141,
                "longitude": 34.11454,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 285,
                "name": "ÇAĞLAYANLAR OTOM. TİC. VE SAN. LTD. ŞTİ.",
                "shortName": "ÇAĞLAYANLAR",
                "code": "98432",
                "mainCode": "40104",
                "address": "MEHMET AKİF ERSOY MAH. FEVZİ ÇAKMAK CAD. NO: 159",
                "district": "MERKEZ",
                "city": "NEVŞEHİR",
                "latitude": 38.60488,
                "longitude": 34.68934,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 164,
                "name": "ÇELİK MOT. ARÇ. SAN. VE TİC. AŞ.",
                "shortName": "ÇELİK",
                "code": "42111",
                "mainCode": "42111",
                "address": "ANKARA YOLU ÜZERİ BÜSAN GİRİŞİ 4. KM. NO:218-220",
                "district": "KARATAY",
                "city": "KONYA",
                "latitude": 37.924,
                "longitude": 32.5267,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 235,
                "name": "ABC MOT.ARÇ.SAN.VE TİC.AŞ.",
                "shortName": "ABC",
                "code": "34442",
                "mainCode": "98131",
                "address": "ÇAĞLAYAN ZENGİN SOK. NO:8",
                "district": "KAĞITHANE",
                "city": "İSTANBUL",
                "latitude": 41.0722,
                "longitude": 28.9798,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 190,
                "name": "ABC MOT.ARÇ.SAN.VE TİC.AŞ.",
                "shortName": "ABC",
                "code": "98131",
                "mainCode": "98131",
                "address": "ABC 5.Levent mahallesi Fatih Sultan Mehmet bulvarı no:19 /1 EYÜPSULTAN",
                "district": "KAĞITHANE",
                "city": "İSTANBUL",
                "latitude": 41.08746,
                "longitude": 28.94121,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 282,
                "name": "ACAMAR OTOMOTİV İNŞAAT SANAYİ TİCARET ANONİM ŞİRKETİ",
                "shortName": "ACAMAR",
                "code": "98433",
                "mainCode": "98433",
                "address": "OVAAKÇA EĞİTİM MH. İSTANBUL CAD. NO: 742 -744",
                "district": "OSMANGAZİ",
                "city": "BURSA",
                "latitude": 40.3066771,
                "longitude": 29.0628525,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 198,
                "name": "ACAR MOT. ARÇ. SAN. VE TİC. A.Ş.",
                "shortName": "ACAR",
                "code": "34149",
                "mainCode": "34149",
                "address": "YENİDOĞAN MH. ENGİNAR SK. NO:24",
                "district": "BAYRAMPAŞA",
                "city": "İSTANBUL",
                "latitude": 41.0397,
                "longitude": 28.91,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 157,
                "name": "ACAR MOT. ARÇ. SAN. VE TİC. A.Ş.",
                "shortName": "ACAR",
                "code": "34428",
                "mainCode": "34149",
                "address": "MALTEPE MH. ÇİFTEHAVUZLAR CD. PRESTİJ İŞ MRK. NO:27",
                "district": "ZEYTİNBURNU",
                "city": "İSTANBUL",
                "latitude": 41.0285,
                "longitude": 28.902,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 248,
                "name": "AKBAK TURİZM SAN.VE TİC.AŞ.",
                "shortName": "AKBAK",
                "code": "06163",
                "mainCode": "06163",
                "address": "ŞEHİT ASTSUBAY ÖMER HALİSDEMİR BULVARI NO:207",
                "district": "KEÇİÖREN",
                "city": "ANKARA",
                "latitude": 39.9799,
                "longitude": 32.8856,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 249,
                "name": "AKKAŞ OTOM. PTR.İNŞ.TRZ.TİC.LTD.ŞTİ.",
                "shortName": "AKKAŞ",
                "code": "10107",
                "mainCode": "10107",
                "address": "PLEVNE MAH. 12122 SOK. NO:7/1",
                "district": "ALTIEYLÜL",
                "city": "BALIKESİR",
                "latitude": 39.614185,
                "longitude": 27.894903,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 214,
                "name": "AKKAŞ OTOM. PTR.İNŞ.TRZ.TİC.LTD.ŞTİ.",
                "shortName": "AKKAŞ",
                "code": "10108",
                "mainCode": "10107",
                "address": "MERKEZ BOSTANCI MAH. EDREMİT-HAVRAN YOLU ÜZERİ ILICA MEVKİİ NO:17 ELF BENZİN İSTASYONU YANI",
                "district": "EDREMİT",
                "city": "BALIKESİR",
                "latitude": 39.573933,
                "longitude": 27.040577,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": false,
                "isExpress": false
            },
            {
                "id": 226,
                "name": "ANTOTO ANTALYA MOT. ARÇ. TİC. SAN. A.Ş.",
                "shortName": "ANTOTO",
                "code": "98395",
                "mainCode": "98395",
                "address": "SARISU MAH. 121 SOKAK NO:8/1",
                "district": "KONYAALTI",
                "city": "ANTALYA",
                "latitude": 36.84557,
                "longitude": 30.598818,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 218,
                "name": "ASAL MOT.ARÇ. SAN.VE TİC.AŞ.",
                "shortName": "ASAL",
                "code": "34444",
                "mainCode": "34701",
                "address": "ATATÜRK OTO SAN.SİTESİ ATA CENTER NO:9/A-B",
                "district": "SARIYER",
                "city": "İSTANBUL",
                "latitude": 41.11233,
                "longitude": 29.020691,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 158,
                "name": "ASF OTOM. A.Ş.",
                "shortName": "ASF",
                "code": "34143",
                "mainCode": "34143",
                "address": "SOĞANLIK YENİ MH. PAMUKKALE SK. NO:2 E-5 YAN YOL",
                "district": "KARTAL",
                "city": "İSTANBUL",
                "latitude": 40.9176,
                "longitude": 29.1768,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 262,
                "name": "ASF OTOM. A.Ş.",
                "shortName": "ASF",
                "code": "41403",
                "mainCode": "34143",
                "address": "E-5 KARAYOLU ÜZERİ İSTASYON MAH. 1460 SK. NO:1",
                "district": "GEBZE",
                "city": "KOCAELİ",
                "latitude": 40.787345,
                "longitude": 29.416215,
                "isRenew": false,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 246,
                "name": "İSOTLAR MOT. OTOM. PTR. TRZ. NAKL. İNŞ. SAN. VE TİC. A.Ş.",
                "shortName": "İSOTLAR",
                "code": "01106",
                "mainCode": "01106",
                "address": "YEŞİLOBA MAH. TURHAN CEMAL BERİKER BULVARI NO:441/1A",
                "district": "SEYHAN",
                "city": "ADANA",
                "latitude": 36.996487,
                "longitude": 35.254143,
                "isRenew": true,
                "isService": true,
                "isSale": true,
                "isVale": true,
                "isExpress": false
            },
            {
                "id": 210,
                "name": "ŞAHİNLER SERVİSÇİLİK SAN.VE TİC.LTD.ŞTİ.",
                "shortName": "ŞAHİNLER",
                "code": "35416",
                "mainCode": "35701",
                "address": "KEMALPAŞA ORGANİZE SANAYİ BÖLGE MAHALLESİ 23 SOK. NO:2 ULUCAK MEVKİİ",
                "district": "KEMALPAŞA",
                "city": "İZMİR",
                "latitude": 38.465098,
                "longitude": 27.365859,
                "isRenew": false,
                "isService": true,
                "isSale": false,
                "isVale": false,
                "isExpress": false
            }
        ]
    }
}